### PR TITLE
Fix dalle3 image generation

### PR DESCRIPTION
**Pull request by pbaranski9411**

### CODE REVIEW

**Comment by cielecki** [comment]
What error those this fix?
This does not look right, as that " )" witll be added immediatelly without waiting fot the entire code

**Comment by cielecki** [comment]
err
there is an error there
but instead of adding it to delta, the id should be added here: tools_requiring_closing_parenthesis

**Comment by cielecki** [comment]
the logic is that in this case we should open the paranthesis, wait for the entire code to stream and then close the paranthesis
(arguments - not code)

**Comment by pbaranski9411** [comment]
@cielecki could you check it right now?

**Review by cielecki — APPROVED** [review]

**Pull request merged**
